export enum ErrorCode {
  APPLICATION_NOT_FOUND = 'APPLICATION_NOT_FOUND',
  INVALID_STATE_TRANSITION = 'INVALID_STATE_TRANSITION',
  FINALIZE_PRECONDITION_FAILED = 'FINALIZE_PRECONDITION_FAILED',
  EXTERNAL_SIMULATION_ERROR = 'EXTERNAL_SIMULATION_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
